### ISSUE TITLE
Request for updated ROS2 info/docs/usage

### ISSUE THREAD

**Issue by cielsys** [ros2/teleop_twist_joy#17] opened 2020-08-26 15:57 UTC
Hi gang
I'm trying to get joystick working and I am finding the documentaion maze of twisty little passages quite frustrating.
I am using apt pkg ros-eloquent-teleop-twist-joy in Eloquent/Ubuntu18.04 desktop-full. This pkg provides a link:
Homepage: http://wiki.ros.org/teleop_twist_joy
But that appears to document only ROS1 which links to the ROS1 git repo (parent of this repo)

Can I suggest that 
The Homepage: http://wiki.ros.org/teleop_twist_joy have some disambiguation between ROS1 vs ROS2, at very least noting that there is a separate, forked ROS2 git repo.

the README for this repo (and perhaps the wiki.ros) have more info about
1) Building/installing from source
2) Invoking with ros2 run - in particular altering axis parameters from cli or param file.

Perhaps I can help with these requests?

Thanks
CL

**Comment by clalancette** [comment] 2020-08-31 12:54
Hi there @cielsys ,

Yeah, I agree that the documentation isn't very good; this was a quick port that I did a long time ago.

You are absolutely right that the http://wiki.ros.org/teleop_twist_joy doesn't have anything about ROS 2.  However, that is mostly by design; we are moving documentation for ROS 2 out of the wiki, so I don't think it makes sense to add disambiguation there.  Unfortunately, we don't currently have a complete package documentation solution for ROS 2 yet.  That being said, we can do better here.  Here's my suggestion:

1.  Change/remove all references to http://wiki.ros.org/teleop_twist_joy in this repository
1.  Update the README with instructions on how to install, build, and run this package.  I'll note that for most users a simple `apt-get install ros-foxy-teleop-twist-joy` should suffice, so the documentation should probably recommend that with a separate section for building from source.

If you are up for that, I'd be happy to review a pull request.  Thanks!

**Comment by cielsys** [comment] 2020-09-04 16:55
Hi @clalancette 
Alrighty. I'll make an attempt to improve the README... But it may be a few weeks before I return to the joystick stuff.
-CL

**Comment by clalancette** [comment] 2020-09-04 16:57
> Alrighty. I'll make an attempt to improve the README... But it may be a few weeks before I return to the joystick stuff.

Sure, no problem.  Thanks.

**Comment by nfry321** [comment] 2020-11-05 13:59
Hi, I came across this issue while trying to work out how to use this package. As I was already writing notes for myself I have turned them into a README and submitted a PR #18 . I'm relatively new to ROS2 and collaborating on github, but I think it is correct!?
I have not included instructions for building from source as I have not attempted it.

**Comment by clalancette** [comment] 2020-11-05 14:46
Fixed by #18 (thanks to @nfry321), so closing out now.

**Closed as completed by clalancette** 2020-11-05 14:46 UTC
Labels: help wanted
